import type { Artisan, Product, Review, Category } from "./types";

export const CATEGORIES: { name: Category; emoji: string; image: string }[] = [
    { name: "Pottery", emoji: "🏺", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=80" },
    { name: "Textiles", emoji: "🧵", image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80" },
    { name: "Paintings", emoji: "🎨", image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=900&q=80" },
    { name: "Bamboo Crafts", emoji: "🎋", image: "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=900&q=80" },
    { name: "Jewelry", emoji: "💍", image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80" },
    { name: "Handicrafts", emoji: "🪔", image: "https://images.unsplash.com/photo-1605883705077-8d3d3cebe78c?auto=format&fit=crop&w=900&q=80" },
];

export const ARTISANS: Artisan[] = [
    {
        id: "a1",
        name: "Ramesh Kumar",
        craft: "Blue Pottery",
        location: "Jaipur",
        state: "Rajasthan",
        bio: "3rd generation master potter from the pink city.",
        story:
            "Ramesh Kumar was nine years old when his grandfather first placed his small hands on a lump of cool, grey-blue clay and said, beta, sun lo — yeh mitti tumse zyaada purani hai. This earth is older than you. It was the summer of 1982, and the family workshop in Kot Jewar — a village just outside Jaipur — was already three generations old. The wheel that Ramesh learned on, a heavy stone disc balanced on a wooden spindle, had been built by his grandfather in 1962 from limestone quarried near Sambhar Lake. It still spins today, and Ramesh's son still throws on it.\n\nFor over four decades, Ramesh ji has shaped sand, fuller's earth and natural cobalt into vessels that carry the calm of Rajasthan's deserts. He works in a craft that contains no clay at all — Jaipur Blue Pottery is made from a mixture of quartz powder, fuller's earth, gum, glass and water, kneaded by hand for three hours every morning before the heat of the day arrives. The tradition itself is foreign-born: it travelled here from Persia in the seventeenth century with the Mughal court, and was almost lost in the early twentieth century until a small handful of families like Ramesh's kept it alive through patronage from the Maharani of Jaipur.\n\nThe family today employs eleven women from Kot Jewar — daughters and daughters-in-law of older potters — who paint the freehand peacocks, lotuses and Persian arabesques that have made Jaipur Blue famous around the world. Ramesh ji's daughter Pooja, who studied commerce at Rajasthan University, now manages the export side of the workshop and translates the family's story into English for international buyers. She is the first woman in three generations of the family to handle the business side. Ramesh ji has been formally recognised twice by the Government of India for his contribution to traditional craft, and he refuses, on principle, to ever use machine-mixed glaze. If a machine can do it, he says, then it is not an art any more. It is a product.",
        avatar: "https://images.unsplash.com/photo-1542144612-1b3641ec3459?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1600&q=80",
        generations: 3,
        rating: 4.9,
        productsCount: 24,
    },
    {
        id: "a2",
        name: "Meera Devi",
        craft: "Banarasi Weaving",
        location: "Varanasi",
        state: "Uttar Pradesh",
        bio: "Weaver of silk poetry on the ghats of Varanasi.",
        story:
            "If you walk through the narrow lanes of Madanpura at four in the morning, before the city of Varanasi has fully woken, you can hear it — the steady, rhythmic clack of wooden punch cards being lifted in sequence by a hundred pit looms. Among them is the loom of Meera Devi, who has been weaving since the age of fourteen.\n\nMeera ji belongs to a family of weavers who have served the looms of Banaras for over a century. Her great-grandfather, who died in 1948, wove for the dowry of an erstwhile princess of Patiala — a single saree that took eight months to complete and is still preserved in the family album as a black-and-white photograph. Her grandfather wove for the wedding of one of the Birla daughters in 1962. Her father wove for the Indian Pavilion at the Tashkent Trade Fair in 1976. Meera ji's own first complete saree, woven when she was sixteen, was bought by a Bengali bride from Howrah and is still worn by her granddaughter on special pujas. This is a family that does not measure time in years but in the sarees that have left its loom.\n\nA single Banarasi saree from Meera ji's loom takes between thirty and forty-five days to weave. The motifs — the kalga buti, the jhallar border, the meenakari floral, the jaali work that imitates the latticework of Mughal palaces — are first sketched on graph paper called naksha, then translated into hundreds of jala punch cards that orchestrate the loom much like a punch-card computer of the 1960s. The pure katan silk comes from Bangalore, the gold zari from Surat, but the soul of the piece is the city itself: Varanasi, the city of light, of shankhanaad at dawn and aarti at dusk.\n\nMeera ji weaves only after a morning bath in the Ganga, and only after she has worn fresh clothes — because, as she says, the saree carries forward whatever the weaver carries within. She runs a small collective of nine women in Madanpura, training young brides who would otherwise have no income of their own. Her dream is to teach her own daughter Ananya, currently studying chartered accountancy in Lucknow, that the loom is not a step backward — it is a quieter, slower way to be very, very modern.",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1600&q=80",
        generations: 4,
        rating: 4.8,
        productsCount: 18,
    },
    {
        id: "a3",
        name: "Lakshmi Bai",
        craft: "Dhokra Metal",
        location: "Bastar",
        state: "Chhattisgarh",
        bio: "Tribal Dhokra artist preserving 4000-year-old lost-wax casting.",
        story:
            "Lakshmi Bai was born in a small village called Kondagaon, deep in the forested heart of Bastar in Chhattisgarh, where the sal trees outnumber the people and the river Indravati carves its slow path to the Godavari. She belongs to the Ghadwa tribe, a community of metal-casters whose technique — Dhokra — is one of the oldest continuous metallurgical traditions on earth. The famous bronze Dancing Girl of Mohenjo-daro, found in the ruins of the Indus Valley Civilization, was cast using the very same lost-wax method that Lakshmi ji uses today, four and a half thousand years later. Nothing about it has been substantially changed.\n\nShe learned the craft from her mother-in-law, Sumitra Bai, who was the last village mid-wife and who taught Lakshmi everything she knew over twenty years of slow afternoons. Lakshmi was twenty-one when she made her first piece — a small votive elephant, four inches tall — and her mother-in-law cried when she saw it, because the elephant's trunk curled to the left, exactly as Sumitra's mother had taught her to make it sixty years earlier in a village fifty kilometers away. The motifs are not decorative. They are language. The peacock means monsoon and motherhood; the elephant is Ganesha; the woman with a matka pot is Lakshmi the giver of wealth; the rider on horseback is the village deity who guards the fields.\n\nLakshmi ji is one of only nine women in her village who still know the full lost-wax process. She winds threads of beeswax mixed with sal-tree resin into impossibly fine spirals over a clay core, by feel alone, in the half-light of her mud home, often with her granddaughter Champa watching silently from the corner. The wax is then encased in a second clay shell, heated until it melts away through small channels, and replaced with molten brass made from scrap utensils donated by neighbours. The mould is broken open afterwards. Each piece is therefore a one-time event — never to be replicated, because the mould that birthed it has already been destroyed.\n\nShe worries about the next generation. Brass scrap is harder to source. The kilns require sal-tree wood, which the forest department now regulates. Her own daughter Sunita knows the craft but works as a nurse in Raipur. Her granddaughter Champa, fourteen years old, has just begun her first wax model — a small horse for a village wedding. Whether the craft survives another generation depends, in part, on whether the world outside Bastar chooses to know that it exists.",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1600&q=80",
        generations: 5,
        rating: 4.7,
        productsCount: 12,
    },
    {
        id: "a4",
        name: "Sita Devi",
        craft: "Madhubani Painting",
        location: "Mithila",
        state: "Bihar",
        bio: "Mithila painter narrating folk tales in natural pigments.",
        story:
            "Sita Devi paints the way her grandmother prayed — slowly, patiently, and with absolute belief that the act itself is more important than the result. She lives in the village of Jitwarpur, not far from Madhubani town in Bihar, in the heart of the ancient kingdom of Mithila. For more than 2,500 years, the women of this region have painted these stories on the walls of their mud homes — first to mark a wedding, then to welcome a birth, then to celebrate a harvest, then simply because the act of painting is itself a form of devotion that does not need an occasion.\n\nSita ji belongs to the Kayastha sub-tradition of Madhubani, which is known for its bold black outlines and a vocabulary of motifs every Mithila woman learns from her grandmother before the age of seven: the lotus that means femininity, the bamboo that means fertility, the fish that means good fortune, the parrot that carries messages between Krishna and Radha, the sun and moon that mean witnesses, the kohbar marriage chamber motif that contains them all. Sita ji learned to paint at the age of seven on the courtyard walls of her grandmother's home, before any of her brothers were sent to school. Painting was, for her generation, the only form of literacy a girl was allowed.\n\nShe was almost married off at sixteen to a farmer in a neighbouring village, but her mother-in-law-to-be, a wise woman named Phoolwati, saw her painting and told the family, she must keep doing this, otherwise she will wither. Sita ji was allowed to paint after marriage, an exception in those years, and she slowly built a reputation with the small handful of buyers from Patna and Delhi who travelled to Mithila in the 1990s in search of authentic folk art.\n\nToday Sita ji runs a small painting school for thirty rural girls in Jitwarpur, teaching them not just the technique but also the stories. She prepares her own canvases by treating handmade cotton with cow-dung paste and a layer of rice flour. Her brushes are twigs of bamboo wrapped in cotton, and a single delicate fine-line brush made from her own hair, replaced once every two months. The pigments are extracted by hand from her kitchen and her garden: turmeric for yellow, hibiscus for red, lampblack from a lamp she keeps burning all night, the juice of bel leaves for green, indigo from the dye-merchant in town. Nothing on her canvas was bought from a shop. As she says, a motif without a story is just a stain on cloth.",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1600&q=80",
        generations: 2,
        rating: 4.9,
        productsCount: 20,
    },
    {
        id: "a5",
        name: "Arjun Reddy",
        craft: "Bamboo Weaving",
        location: "Tripura",
        state: "Tripura",
        bio: "Bamboo artisan crafting eco-luxury home decor.",
        story:
            "Arjun grew up in the bamboo groves of Tripura where his grandmother, before cutting any bamboo, would knock three times on the stalk with her curved knife and listen. If the sound was hollow and clear, the bamboo was ready. If it was dull, she would walk on. This is how Tripura's tribal weavers — the Reang, the Kokborok, the Tripuri — have spoken to bamboo for centuries. Not as a material to be used, but as a relative to be asked permission of.\n\nArjun was an unusual child for his village. He left Agartala at seventeen to study product design at the National Institute of Design in Ahmedabad, on a scholarship for students from the Northeast. His batchmates designed for Apple and Samsung; he designed for his grandmother. After four years in the gleaming labs of NID, he came back home with a single conviction: that craft and contemporary aesthetics are not enemies, that the bambu-jali hexagonal weave his grandmother taught him as a child was, in its own way, as elegant as anything he had seen in a museum in Milan.\n\nHis workshop in Agartala employs eighteen artisans from four tribal communities and operates almost entirely on solar power. He harvests only mature moso bamboo, at least four years old, always at full moon when the sap has risen. The canes are cured for thirty days in smoke from a wood-fired chulha — a process that protects them from termites for three decades and gives them a faint, beautiful sweetness that you can smell when you first unbox a piece. Arjun keeps a notebook in which he writes the name of every artisan, the village they came from, and the date a piece was completed. Each finished product carries a small jute tag with this information.\n\nHis pendant lamps now light cafes in Berlin, restaurants in Tokyo, design studios in Brooklyn. But Arjun's proudest moment was not an export order — it was the day his grandmother, now in her late eighties, came to the workshop and saw the bambu-jali pattern she had taught him as a child, scaled up to form a four-foot-wide ceiling installation. She touched it for a long time without speaking. Then she said in Kokborok, the bamboo remembers.",
        avatar: "https://images.unsplash.com/photo-1542144612-1b3641ec3459?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1600&q=80",
        generations: 2,
        rating: 4.8,
        productsCount: 15,
    },
    {
        id: "a6",
        name: "Fatima Sheikh",
        craft: "Kashmiri Pashmina",
        location: "Srinagar",
        state: "Kashmir",
        bio: "Hand-spinning the world's finest pashmina in the valley.",
        story:
            "Fatima Sheikh hand-spins changthangi wool that travels from the highlands of Ladakh to her wheel in the old quarters of Srinagar. She comes from a family of pashmina spinners that has worked for the Kashmiri royal court since the days of Maharaja Hari Singh, and before that for the Dogra rulers of the nineteenth century. The wooden charkha she uses today was made by her great-grandfather in 1923. It is balanced so finely that a single human breath can set it spinning.\n\nTrue pashmina, Fatima ji will tell you, is not a fabric. It is a journey. It begins at 14,500 feet on the Changthang plateau of Ladakh, where the rare Changthangi goat — sometimes called the cashmere goat — survives winters of minus forty degrees by growing an undercoat finer than a strand of human hair, between twelve and fourteen microns in diameter. Each spring, when the snow begins to melt, Changpa nomads gently comb this fleece by hand from the goat's belly. A single goat yields just eighty grams a year. The fleece travels on the back of mules over the Zojila pass to Srinagar, where Fatima receives it in small, fragrant bales smelling of the high mountain.\n\nShe cleans the fleece grain by grain on a wooden tray, separating the soft inner fibres from the coarse outer guard hairs, a process that takes three full days for the wool needed for a single shawl. Then she hand-spins it on her great-grandfather's charkha, so gently that no machine has ever replicated her touch. Machine spinning would shred fibres this fine. Fatima ji learned this from her mother, Habiba, who learned from her grandmother Razia, who span pashmina for the last Maharaja's daughter as part of her dowry in 1925. While she works, Fatima sings folk songs of the Vale called wanwun, and she believes those songs are spun into the yarn itself.\n\nAfter the floods of 2014 destroyed her workshop and most of her family's ancestral spinning tools, Fatima rebuilt with a small grant from a Delhi-based foundation. She now runs a women-only spinning circle of twenty-two artisans aged sixteen to seventy-eight. The youngest, Saima, lost her father to the floods. The oldest, Khaleda Bibi, is Fatima's own grandmother. Together they spin between four and five shawls a month, and the wait list to buy one is currently fourteen months long.",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=400&q=80",
        cover: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1600&q=80",
        generations: 3,
        rating: 5,
        productsCount: 10,
    },
];

export const PRODUCTS: Product[] = [
    {
        id: "p1",
        title: "Jaipur Blue Pottery Vase",
        category: "Pottery",
        price: 1200,
        originalPrice: 1500,
        rating: 4.9,
        reviews: 128,
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a1",
        badge: "AI Featured",
        description:
            "A turquoise vase glazed with the cobalt of the Aravalli sky, hand-thrown on a wheel that has spun since 1962. Decorated with freehand peacock motifs in lapis blue and emerald green.",
        story:
            "The story of this vase begins not in a kiln, but in the salt deserts of Rajasthan, where Ramesh Kumar's grandfather first learned to mix quartz powder with fuller's earth, gum and glass. The technique itself travelled here from Persia in the seventeenth century, carried by craftsmen who served the Mughal court before settling along the trade routes that ran through Jaipur. Local royal patronage from the Maharani of Jaipur kept the craft alive when other workshops closed during the lean decades of the early twentieth century.\n\nWhat makes Jaipur Blue truly unique is that it contains no clay — only stone dust, sand and natural binders, fired at low temperature until it becomes lighter than ceramic and harder than porcelain. Ramesh ji wakes at four every morning to knead the dough by hand for two hours, because the rhythm cannot be replicated by machines. The dough has the consistency of soft mochi, and must be worked until it stops resisting. Only then can it be shaped on the wheel.\n\nHis daughter Pooja paints the peacocks freehand, never tracing, never copying — each bird is a slightly different tilt of the head. The cobalt comes from a single mine near Ajmer, and the glaze is a closely-guarded family recipe that Ramesh ji's grandfather adapted from a Persian formula in the 1950s. When the vase emerges from the wood-fired kiln after eighteen hours of slow firing, the family pours rosewater over it as an offering to Devi Saraswati. You are not buying ceramic. You are buying four hundred years of trans-Himalayan craft, three generations of patience, and a small piece of the Jaipur sky.",
        hashtags: ["#JaipurBlue", "#HandmadeIndia", "#PotteryLove", "#IndianCrafts", "#HomeDecor"],
        location: "Jaipur, Rajasthan",
        inStock: 12,
    },
    {
        id: "p2",
        title: "Banarasi Silk Dupatta",
        category: "Textiles",
        price: 3500,
        rating: 4.8,
        reviews: 96,
        image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a2",
        badge: "Bestseller",
        description:
            "Pure katan silk woven with real zari, kissed by the loom for 22 days. A hue called Holi-orange, kissed with hints of marigold and rose.",
        story:
            "In the bylanes of Madanpura in Varanasi, a single Banarasi dupatta is born from the music of fifty wooden punch cards being lifted in sequence by Meera Devi's pit loom. She inherited this loom from her father, who inherited it from his — a chain of weavers stretching back to the 1890s when the Mughal aesthetic still flowered along the ghats of the Ganga.\n\nEach motif on this dupatta — the kalga buti curling like a paisley flame, the jhallar border with its row of tiny suns, the meenakari floral that mimics enamelwork on jewellery — was first sketched by Meera ji's husband on graph paper called naksha, then translated into hundreds of jala punch cards that orchestrate the loom much like a punch-card computer of the 1960s.\n\nThe pure katan silk comes from Bangalore, the gold zari from Surat, but the soul of the piece is Varanasi: the city of light, of shankhanaad at dawn and aarti at dusk. Meera ji weaves only when she has bathed in the Ganga and worn fresh clothes, because she believes the saree must carry no impurity from her hands. Twenty-two days, fourteen hours a day, with breaks only for prayer and meals brought to her loom by her daughter-in-law.\n\nYou see four metres of fabric. The loom remembers three hundred and eight hours of one woman's life.",
        hashtags: ["#Banarasi", "#SilkSaree", "#HandloomLove", "#MadeInIndia", "#WeaversOfIndia"],
        location: "Varanasi, Uttar Pradesh",
        inStock: 5,
    },
    {
        id: "p3",
        title: "Dhokra Brass Necklace",
        category: "Jewelry",
        price: 850,
        rating: 4.7,
        reviews: 64,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a3",
        badge: "Trending",
        description:
            "Tribal lost-wax cast neckpiece with peacock and elephant motifs. Each necklace is one of one — the mold breaks after a single use.",
        story:
            "Lakshmi Bai's village in Bastar has cast metal this way since the time of Mohenjo-daro. Dhokra is one of the oldest continuous metallurgical traditions in the world, and the technique has not changed in 4,500 years.\n\nIt begins with a clay core shaped by hand from termite-mound soil, which has the right plasticity. Over this, Lakshmi ji winds threads of beeswax mixed with sal-tree resin into impossibly fine spirals. She does this by feel alone, in the half-light of her mud home, often with her granddaughter Champa watching silently from the corner. The wax model is then encased in a second clay shell with channels left for venting, and heated until the wax melts away through those channels — the lost wax. Molten brass, made from scrap utensils donated by neighbours, is poured in. After cooling, the clay is broken open and the necklace is revealed, smelling of earth and fire, never to be replicated because the mould itself is destroyed in the act of birth.\n\nThe peacock motif is sacred to the Gond tribe — it represents both monsoon and motherhood, the two great providers of life in the forest. The elephant is the deity Ganesh, who removes obstacles from the path of the wearer. Lakshmi ji is one of only nine women in her village who still know this craft. She is teaching her daughter Sunita, but Sunita works as a nurse in Raipur and can only practice on weekends.",
        hashtags: ["#Dhokra", "#TribalArt", "#HandmadeJewelry", "#IndianHeritage", "#BohoStyle"],
        location: "Bastar, Chhattisgarh",
        inStock: 8,
    },
    {
        id: "p4",
        title: "Madhubani Painting on Canvas",
        category: "Paintings",
        price: 2200,
        originalPrice: 2750,
        rating: 4.9,
        reviews: 142,
        image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a4",
        badge: "20% Off",
        description:
            "Krishna and Radha under the kadamba tree, painted with natural pigments on handmade cotton canvas. Pigments derived from turmeric, marigold, lampblack and bel leaves.",
        story:
            "For more than two and a half thousand years, the women of Mithila have painted these stories on the walls of their mud homes — first to mark a wedding, then to welcome a birth, then to celebrate a harvest, then simply because the act of painting is itself a form of devotion that does not need an occasion. Sita Devi belongs to the Kayastha sub-tradition, which is known for its bold black outlines and a vocabulary of motifs every Mithila woman learns from her grandmother by the age of seven.\n\nThis painting depicts the rasalila — the cosmic dance under the kadamba tree on the banks of the Yamuna. Krishna stands at the centre playing his bansuri, with Radha and the gopis turning around him in a circle of love that contains the universe. The lotus at the bottom means femininity. The bamboo in the corners means fertility. The pair of fish in the water means good fortune. The two parrots in the kadamba tree carry messages between the lovers. The sun and moon at the top are witnesses to the dance.\n\nSita ji prepared the canvas herself by treating handmade cotton with cow-dung paste, then a layer of rice flour, then sun-drying for three full days. Her brushes are twigs of bamboo wrapped in cotton, and a single delicate fine-line brush made from her own hair, replaced once every two months. The pigments are extracted by hand from her kitchen and her garden: turmeric for yellow, hibiscus for red, lampblack from a lamp she keeps burning all night, the juice of bel leaves for green, indigo from the dye-merchant in Madhubani town.\n\nThe painting took seventeen days, and on the eighteenth day Sita ji touched her forehead to it, the way a mother touches her newborn. Hang it where afternoon sun falls — Mithila pigments brighten as they age in light, the way memories do.",
        hashtags: ["#Madhubani", "#MithilaArt", "#FolkArt", "#IndianPainting", "#Krishna"],
        location: "Mithila, Bihar",
        inStock: 4,
    },
    {
        id: "p5",
        title: "Bamboo Pendant Lamp",
        category: "Bamboo Crafts",
        price: 1850,
        rating: 4.8,
        reviews: 71,
        image: "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a5",
        badge: "New",
        description:
            "Hand-woven bamboo pendant lamp that throws lattice shadows like a Tripura sunrise. Pairs with warm white LED for that golden hour glow.",
        story:
            "Arjun grew up in the bamboo groves of Agartala where his grandmother, before cutting any bamboo, would knock three times on the stalk with her curved knife and listen. If the sound was hollow and clear, the bamboo was ready. If it was dull, she would walk on. This is how Tripura's tribal weavers have spoken to bamboo for centuries — not as a material, but as a relative whose permission must be asked.\n\nArjun harvests only mature moso bamboo at least four years old, always at full moon when the sap has risen, then cures the canes for thirty days in smoke from his grandmother's wood-fired chulha. This protects the bamboo from termites for three decades and gives it a faint, beautiful sweetness you can smell when you first unbox the lamp. After curing, each cane is split by hand into strips of exactly three millimetres, and only the inner two layers — the most flexible part — are used for weaving.\n\nThe weave on this lamp is called bambu-jali, a hexagonal lattice pattern that the Reang community has traditionally used in fishing baskets and rice-storage containers. Arjun took that pattern, reduced it by half, and married it with a modern brushed-brass fitting designed by his cousin who studied at NIFT Shillong. The design has been featured in Architectural Digest India and now lights cafes in Berlin and Brooklyn.\n\nEach lamp takes seven days. The weaver is named Nandita, twenty-six years old, mother of two, and on the small jute tag inside every lamp you will find her name and her village. When you switch the lamp on, the shadows it throws on your walls are completely unique — no two looms in his workshop produce identical patterns. The shadows are the bamboo's own signature, written in light.",
        hashtags: ["#BambooCraft", "#EcoDecor", "#TripuraArt", "#Sustainable", "#HomeLighting"],
        location: "Agartala, Tripura",
        inStock: 9,
    },
    {
        id: "p6",
        title: "Kashmiri Pashmina Shawl",
        category: "Textiles",
        price: 12500,
        rating: 5,
        reviews: 38,
        image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a6",
        badge: "AI Featured",
        description:
            "Ring-passable pashmina hand-spun from Changthangi goat wool. Lighter than a whisper, warmer than a fireplace.",
        story:
            "True pashmina is not a fabric. It is a journey. It begins at fourteen and a half thousand feet on the Changthang plateau of Ladakh, where the rare Changthangi goat survives winters of minus forty degrees by growing an undercoat finer than a strand of human hair — between twelve and fourteen microns. Each spring, when the snow begins to melt, Changpa nomads gently comb this fleece by hand from the goat's belly. A single goat yields just eighty grams a year. To make this single shawl required the gentle combings of nearly twenty goats.\n\nThe fleece travels on the back of mules over the Zojila pass to Srinagar, where Fatima Sheikh receives it in small, fragrant bales smelling of the high mountain. She cleans it grain by grain on a wooden tray, separating the soft inner fibres from the coarse outer guard hairs, a process that takes three full days. Then she hand-spins it on a charkha so gentle that no machine has ever replicated it. Machine spinning would shred fibres this fine. Fatima ji learned this from her mother, who learned it from a grandmother who span pashmina for the last Maharaja of Kashmir's daughter as part of her dowry in 1925.\n\nWhile she works, she sings folk songs of the Vale called wanwun, and she believes those songs are spun into the yarn itself. After spinning, the yarn passes to a male weaver who works it on a wooden loom for fourteen days. After weaving, it goes to a kani-kar who gently presses it with a smooth river stone. Total labour: just over seven hundred hours.\n\nThe finished shawl is so fine that, in the old test of authenticity, it can be drawn through a wedding ring. Hold it to the light. You can see the city of Srinagar shining through the weave.",
        hashtags: ["#Pashmina", "#Kashmir", "#LuxuryShawl", "#HeirloomWeave", "#HandSpun"],
        location: "Srinagar, Kashmir",
        inStock: 3,
    },
    {
        id: "p7",
        title: "Terracotta Diya Set of 12",
        category: "Pottery",
        price: 450,
        rating: 4.6,
        reviews: 213,
        image: "https://images.unsplash.com/photo-1605883705077-8d3d3cebe78c?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a1",
        badge: "Trending",
        description:
            "Set of 12 hand-pinched terracotta diyas. A Diwali ritual, lit and ready. Comes with cotton wicks and a gift card with the artisan's name.",
        story:
            "These diyas are made not on a wheel but between the palms of two hands — a technique called chimti, the pinch method, which is the oldest form of pottery in India and predates the wheel by thousands of years. Ramesh ji's youngest apprentices, ten and twelve years old, learn chimti before they ever touch a wheel. It is the alphabet of the craft.\n\nThe clay comes from the banks of the Banas river, sun-dried, sieved through fine cotton, and aged for three weeks in a covered earthen pot mixed with water and a small amount of paddy chaff. Each diya is shaped in under three minutes, with a slight irregularity that makes it human. Two pinches form the bowl, one for the lip, one for the slot where the wick will rest.\n\nOn the night of Lakshmi Puja, Ramesh ji's family lines a hundred of these on the wall of their courtyard and waits for the elder women to light the first flame. The youngest grandchild is held up to light the second. By the third, the courtyard glows like a constellation of small orange suns. There is a saying in Rajasthan: jab maati jalti hai, ghar muskurata hai. When the earth itself burns, the home smiles.\n\nThe set you receive comes with twelve diyas and a small thank-you note hand-written in Hindi by the apprentice who shaped them. Light them slowly, one by one. Let the wax of routine melt, and let the room remember what fire used to mean.",
        hashtags: ["#Diya", "#Diwali", "#Terracotta", "#FestiveDecor", "#IndianTradition"],
        location: "Jaipur, Rajasthan",
        inStock: 50,
    },
    {
        id: "p8",
        title: "Silver Filigree Earrings",
        category: "Jewelry",
        price: 1650,
        rating: 4.8,
        reviews: 56,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a3",
        description:
            "Cuttack tarakasi silver work bent into chand-bali drops. Each thread thinner than a human hair, drawn 28 times through diminishing dies.",
        story:
            "Tarakasi — the silver filigree of Cuttack — arrived in Odisha along the maritime spice routes from Persia and Java around the tenth century. It found a home in the temples of the Bay, where artisan families have practiced it ever since. The Jagannath temple at Puri still uses tarakasi silver in its annual Rath Yatra rituals.\n\nTo make a single thread for these earrings, a silver bar weighing about forty grams is repeatedly drawn through twenty-eight successively smaller dies until it emerges as a fine wire thinner than a strand of human hair — finer than a strand of pashmina wool. The wire is then twisted, hammered flat, and bent by tweezers into spirals, leaves and crescents — the chand-bali, or moon-shaped drop, that has framed Indian women's faces since the Chola dynasty.\n\nThese earrings were made by Sanatan, a young apprentice in Lakshmi Bai's extended workshop network, as part of his guru-shishya year. He could not buy his own silver, so the workshop supplied him twelve grams; he returned eleven point six grams of finished work, the difference being the inevitable dust of his learning, swept up at the end of each day and carefully resmelted for the next apprentice. Each chand-bali contains eighty-seven tiny components, all soldered together with such precision that the earring weighs less than a grape.\n\nLook closely at the centre of each drop. There is a microscopic asymmetry — a tiny tilt that no master would have allowed himself. That is Sanatan's signature, the takhallus that an apprentice hides in every piece, like a young poet putting his name into the last line of his first ghazal.",
        hashtags: ["#Filigree", "#SilverJewelry", "#Tarakasi", "#HandmadeJewelry", "#TraditionalArt"],
        location: "Cuttack, Odisha",
        inStock: 14,
    },
    {
        id: "p9",
        title: "Pattachitra Krishna Scroll",
        category: "Paintings",
        price: 4200,
        rating: 4.9,
        reviews: 47,
        image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a4",
        badge: "AI Featured",
        description:
            "A 36-inch hand-painted Pattachitra scroll narrating the dashavatara — the ten incarnations of Vishnu — in mineral and vegetable pigments on tussar silk.",
        story:
            "Pattachitra — literally cloth-painting — has been the visual liturgy of Puri's Jagannath temple for over a thousand years. It is one of the few crafts in India where the artist is also a priest. The painters of Raghurajpur, a small village twelve kilometres from the Jagannath temple, are the official chitrakaras of the deity, and during the famous fortnight when the deities are renewed every twelve years, only Raghurajpur painters may touch them.\n\nBefore beginning this scroll, the painter — who learned from Sita Devi during her residency in Raghurajpur and who belongs to the tradition formally — fasted for one full day and bathed in the Bay of Bengal at dawn. He then prepared the canvas himself: two layers of fine cotton glued together with tamarind seed paste, polished with a smooth stone for two days until it became as taut as drum-skin.\n\nThe pigments are entirely indigenous: white from conch shells crushed and soaked for a week, red from cinnabar mined in Khurda, yellow from the haritala stone, black from the soot collected over a coconut-oil lamp burned for three nights, blue from indigo plants grown in the artist's own backyard. The figures of Krishna's ten avatars — from Matsya the fish through Kurma the tortoise, Varaha the boar, Narasimha the man-lion, Vamana, Parashurama, Rama, Krishna himself, Buddha, all the way to Kalki the prophesied warrior on a white horse — are drawn first in chalk, then with confident brush-strokes that have no margin for error.\n\nThe final touches are the jewellery on each avatar, painted with such fine precision that he uses a brush made from a single squirrel hair. The scroll is then sealed with a coat of pure beeswax that gives it a soft sheen and protects it for two centuries. This is not decoration. It is a living temple, rolled.",
        hashtags: ["#Pattachitra", "#OdishaArt", "#HinduArt", "#TraditionalPainting", "#Krishna", "#FolkArt"],
        location: "Raghurajpur, Odisha",
        inStock: 6,
    },
    {
        id: "p10",
        title: "Channapatna Wooden Toy Set",
        category: "Handicrafts",
        price: 980,
        rating: 4.7,
        reviews: 184,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a1",
        badge: "Bestseller",
        description:
            "A set of five Channapatna toys — the famous lacquered wooden figures of Karnataka, safe enough for newborns to chew, beautiful enough for grown-ups to keep on a shelf.",
        story:
            "Channapatna sits halfway between Bangalore and Mysuru on the old highway, in a small town that has earned the title Gombegala Ooru — the town of toys. Every second house here is a workshop, and the air carries the faint, sweet smell of lac and ivory-wood shavings from morning till evening. Roughly six thousand artisans depend on this craft for their livelihood.\n\nThe craft began in the late eighteenth century, when Tipu Sultan, fascinated by Persian toy-makers, invited artisans from the Middle East to teach his subjects. They brought with them the technique of turning soft ivory-wood — locally called doodhi or aale-mara — on a hand-lathe, then colouring it with lac dyes derived from the secretions of female lac insects on the kusum tree. The lac is melted, mixed with vegetable pigments — turmeric for yellow, indigo for blue, ratnajyoti seeds for red, the bark of the rohini tree for orange — and applied while the toy spins on the lathe, friction generating just enough heat to melt the dye into the wood.\n\nBecause no chemical paint is used, these toys are completely food-safe and have been certified by AYUSH for use with infants. A baby can chew on them, drop them in a wet mouth, leave them on the floor for the family dog to lick, and they will come out completely safe. The colours will not run.\n\nThe set you receive comes from a workshop run by Shivanna, a fourth-generation maker who employs eleven women from his village. He has been promised a Geographical Indication mark by the government, but what means more to him is that his daughter Nandita, who studied software engineering and worked for three years at Infosys in Bangalore, has just returned home to manage exports. The lathe will keep turning for another generation.",
        hashtags: ["#Channapatna", "#WoodenToys", "#KarnatakaCraft", "#EcoFriendly", "#KidsToys", "#GIProduct"],
        location: "Channapatna, Karnataka",
        inStock: 22,
    },
    {
        id: "p11",
        title: "Kantha Embroidered Stole",
        category: "Textiles",
        price: 2400,
        originalPrice: 3000,
        rating: 4.8,
        reviews: 91,
        image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a2",
        badge: "20% Off",
        description:
            "Hand-embroidered kantha stole in Bengal cotton-silk. Layered from old saris, stitched with a running thread of love by a women's collective in Shantiniketan.",
        story:
            "Kantha is the embroidery of memory. For centuries, the women of rural Bengal have layered their old, soft saris together and bound them with a simple running stitch — turning what was once bridal trousseau or a grandmother's daily wear into quilts, throws and stoles for the next generation. To stitch kantha is to literally stitch the past into the future.\n\nThis stole comes from the Surovi Mahila Samiti, a collective of forty-six women in a village near Shantiniketan, where Rabindranath Tagore once dreamed of a school under the trees. Each stole is a collaboration: one woman lays the layers and bastes them together, another sketches the motifs in light pencil, and seven to eight women take turns stitching across many quiet afternoons under the neem tree where the elders gather.\n\nThe motifs on this piece — a leaping fish, a lotus in full bloom, a paddy field with the tiny figures of women planting, a small boat on the river — are taken from a 1970s sari that belonged to the mother of Rasmani Kakima, the eldest member of the collective, now seventy-nine years old. She brought the sari out of her family trunk one morning, wept softly, and said in Bengali, let her travel.\n\nThe thread is mercerised cotton from Murshidabad, hand-dyed with marigold petals and pomegranate skin in a traditional copper vessel. Each stitch is roughly two millimetres apart, and there are an estimated thirty-eight thousand stitches in this single stole. When you wear it, you carry a women's collective, a Tagore village, and Rasmani Kakima's mother, all at once.",
        hashtags: ["#Kantha", "#BengalCraft", "#HandEmbroidery", "#WomenWeavers", "#Shantiniketan", "#SlowFashion"],
        location: "Shantiniketan, West Bengal",
        inStock: 11,
    },
    {
        id: "p12",
        title: "Bidri Vase with Silver Inlay",
        category: "Handicrafts",
        price: 5800,
        rating: 4.9,
        reviews: 29,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a3",
        badge: "AI Featured",
        description:
            "A 9-inch Bidri vase — black zinc alloy inlaid with pure silver wire in a Mughal jali pattern. The contrast between matte black and gleaming silver is the soul of the Deccan.",
        story:
            "Bidriware was born in the fourteenth century in the town of Bidar in present-day Karnataka, where the Bahmani Sultans built their citadel and brought with them artisans from across the Persian world. There is no other craft on earth that uses Bidar's specific local soil, which contains a rare iron-oxide compound that gives the alloy its deep, unfading black colour. Soil from anywhere else simply will not work.\n\nTo make this vase, the artisan, a master named Abdul Rauf, first cast it in an alloy of ninety-four parts zinc to six parts copper. The alloy itself is the result of a five-hundred-year-old recipe. He then engraved the pattern by hand with a chisel, working in candlelight to better see the shadows of his lines. Pure silver wire, drawn down to the thickness of a child's hair, was then hammered into those grooves — not glued, not soldered, but locked in by friction, the way wedge-stones lock in a Mughal arch.\n\nThen comes the moment of magic. The vase is buried for a full day in a slurry made from Bidar's special soil mixed with ammonium chloride, salt, and boiled rainwater. Something miraculous happens in that mud bath: the iron-oxide turns the zinc alloy permanently jet-black, but does not touch the silver. When the vase is unearthed and gently washed, the silver design suddenly leaps out in dazzling contrast against the matte black field — the famous chand-tara effect, moon and stars.\n\nOnly fifty true Bidri masters remain in Bidar today. Each piece is registered with a GI tag. This vase carries number BR-2026-1184, and Abdul Rauf's name etched discreetly into the base. He is sixty-three years old and has been working at it since he was seven.",
        hashtags: ["#Bidri", "#DeccanArt", "#MughalCraft", "#GIProduct", "#LuxuryDecor", "#SilverInlay"],
        location: "Bidar, Karnataka",
        inStock: 4,
    },
    {
        id: "p13",
        title: "Bamboo Tea Coaster Set",
        category: "Bamboo Crafts",
        price: 380,
        rating: 4.6,
        reviews: 156,
        image: "https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a5",
        description:
            "Set of six woven bamboo coasters with hand-stitched cotton edging. Made by a youth collective in Assam who plant a bamboo seedling for every set sold.",
        story:
            "These coasters come from the Brahmaputra valley, where Arjun's network of artisans includes the Subansiri Youth Bamboo Collective — twenty-three young men and women, average age twenty-two, all from families displaced by the catastrophic Assam floods of 2020. The collective was set up by a former MNREGA worker named Hiren Da, fifty-one years old, who realised after the floods that bamboo grows back in eighteen months even on flood-soaked land.\n\nThe bamboo for these coasters comes from a five-acre plot the collective planted three years ago and now harvests sustainably — never more than thirty percent of any clump in a single season, and always leaving the youngest shoots untouched. The plot doubles as a flood barrier, because mature bamboo roots bind the soil better than concrete walls and at a fraction of the cost.\n\nEach coaster takes about twenty-five minutes to weave on a small wooden jig that Hiren Da designed himself, copying a sketch from an old Forest Department manual from 1962. The cotton edging is hand-stitched by Hiren Da's wife, Roxy, using thread dyed with mati-tel — a traditional Assamese tea-and-iron mordant that produces the warm rust colour you see on the rim.\n\nFor every set sold through KalaSetu, the collective plants one new seedling at the riverbank to strengthen the soil against the next monsoon. So far, four thousand two hundred seedlings stand because of buyers like you. The seedlings have names. The collective sends a photograph of yours, six months after planting, to the email you used to check out.",
        hashtags: ["#BambooCraft", "#AssamCraft", "#SustainableLiving", "#YouthCollective", "#FloodResilience", "#PlantedForYou"],
        location: "Lakhimpur, Assam",
        inStock: 38,
    },
    {
        id: "p14",
        title: "Meenakari Silver Earrings",
        category: "Jewelry",
        price: 2150,
        rating: 4.7,
        reviews: 73,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80",
        artisanId: "a6",
        badge: "New",
        description:
            "Sterling silver jhumkas with peacock-blue and pomegranate-red Meenakari enamel. Inspired by the jharokhas of City Palace, Jaipur.",
        story:
            "Meenakari — the art of fusing coloured enamel onto metal — entered India through Raja Man Singh of Amber, who was so taken by Persian enamellers at the Mughal court that he invited five master meenakars from Lahore to settle in Jaipur in 1590. Their descendants still live in the Gopalji-ka-Rasta district of the old pink city, in workshops the size of small kitchens, lit by single bare bulbs and the orange glow of charcoal hearths. The same families. The same lanes. Five hundred years of unbroken practice.\n\nTo make these earrings, the artist first cast pure sterling silver jhumkas in the bell shape that has been the Indian ear-drop since the Cholas. He then engraved tiny wells called khaaps into the surface — about a hundred and forty wells per earring, each smaller than a sesame seed. Powdered glass mixed with metal oxides — cobalt for blue, iron for red, copper for green — was placed grain by grain into each well using a fine needle.\n\nThe piece was then fired at exactly eight hundred and fifty degrees in a small kiln. The temperature is critical: ten degrees too low and the enamel never fuses; ten degrees too high and the silver itself begins to soften. The artist then re-engraves any flaws, refills, and re-fires the piece five separate times — once for each colour — because each enamel melts at a slightly different temperature and they cannot be applied together.\n\nAfter the final firing, the surface is polished by hand with fine sand and lemon juice until it gleams like a stained-glass window in miniature. Each pair takes seven days. Hold them up to a window. You will see why Mughal poets compared them to jharokhas — small windows of paradise.",
        hashtags: ["#Meenakari", "#JaipurCraft", "#SilverJewelry", "#Jhumkas", "#MughalArt", "#EnamelArt"],
        location: "Jaipur, Rajasthan",
        inStock: 9,
    },
];

export const REVIEWS: Review[] = [
    { id: "r1", productId: "p1", author: "Priya Singh", rating: 5, comment: "Absolutely stunning craftsmanship. The colour came out brighter than the photos. Worth every rupee.", date: "2 weeks ago" },
    { id: "r2", productId: "p1", author: "Aakash Patel", rating: 5, comment: "Came beautifully packed in jute. The story card inside made me cry a little.", date: "1 month ago" },
    { id: "r3", productId: "p2", author: "Sneha R.", rating: 5, comment: "The drape, the fall, the zari... I felt like I was wearing history.", date: "3 weeks ago" },
    { id: "r4", productId: "p4", author: "Daniel K.", rating: 5, comment: "Shipping to Berlin was fast. The painting is now my living room's heartbeat.", date: "5 days ago" },
    { id: "r5", productId: "p9", author: "Anjali Mehta", rating: 5, comment: "The Pattachitra is breathtaking. Each avatar is so detailed I keep finding new things every day.", date: "1 week ago" },
    { id: "r6", productId: "p10", author: "Kavya Iyer", rating: 5, comment: "My toddler loves these. And I love that they are truly food-safe and locally made.", date: "2 weeks ago" },
    { id: "r7", productId: "p11", author: "Ria Banerjee", rating: 5, comment: "Stitched with such love. The story behind it brought me to tears.", date: "10 days ago" },
    { id: "r8", productId: "p12", author: "Rajesh Khanna", rating: 5, comment: "The contrast of black and silver is mesmerising. A statement piece.", date: "3 weeks ago" },
];

export const TESTIMONIALS = [
    {
        name: "Lakshmi Bai",
        role: "Dhokra Artisan, Bastar",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=200&q=80",
        quote: "Pehle main sirf mela mein bechti thi. KalaSetu AI ne meri necklace ko Mumbai aur London tak pahuncha diya.",
    },
    {
        name: "Ramesh Kumar",
        role: "Blue Potter, Jaipur",
        avatar: "https://images.unsplash.com/photo-1542144612-1b3641ec3459?auto=format&fit=crop&w=200&q=80",
        quote: "I just record my voice describing the vase. The AI writes my Instagram caption in better English than my son.",
    },
    {
        name: "Meera Devi",
        role: "Banarasi Weaver",
        avatar: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=200&q=80",
        quote: "Mere har saree ki kahani ab duniya tak pahunchti hai - in my own Hindi, translated beautifully.",
    },
];

export const SALES_DATA = [
    { month: "Jan", sales: 12000, orders: 18 },
    { month: "Feb", sales: 18500, orders: 24 },
    { month: "Mar", sales: 24200, orders: 32 },
    { month: "Apr", sales: 21000, orders: 28 },
    { month: "May", sales: 32800, orders: 41 },
    { month: "Jun", sales: 39500, orders: 49 },
    { month: "Jul", sales: 45200, orders: 58 },
    { month: "Aug", sales: 51000, orders: 64 },
    { month: "Sep", sales: 48800, orders: 61 },
    { month: "Oct", sales: 62300, orders: 78 },
];

export const CATEGORY_SALES = [
    { name: "Pottery", value: 32 },
    { name: "Textiles", value: 28 },
    { name: "Jewelry", value: 18 },
    { name: "Paintings", value: 12 },
    { name: "Bamboo", value: 6 },
    { name: "Other", value: 4 },
];
